name: Update Readme | 更新README

on:
  schedule:
    - cron: "0 8,20 * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'misitebao/misitebao'

    steps:
      - name: Checkout | 切换到部署分支
        uses: actions/checkout@v3
        with:
          ref: "main"
          submodules: true
          fetch-depth: 0

      - name: Setup Git | 设置Git
        run: |
          git config --local user.email "i@misitebao.com"
          git config --local user.name "Misite Bao"

      - name: Setup Go | 设置Go
        uses: actions/setup-go@v4

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Update Data
        run: |
          task update-data
